"""initial migration

Revision ID: be5c4de9546c
Revises: 
Create Date: 2024-10-03 06:51:12.284268

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "be5c4de9546c"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "booking_requests",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event_time", sa.DateTime(), nullable=True),
        sa.Column("address", sa.JSON(), nullable=False),
        sa.Column("duration_minutes", sa.SmallInteger(), nullable=False),
        sa.Column("topic", sa.String(), nullable=False),
        sa.Column("requested_by", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_booking_requests_id"), "booking_requests", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_booking_requests_id"), table_name="booking_requests")
    op.drop_table("booking_requests")
    # ### end Alembic commands ###
