site_name: Booking Service API 

theme:
  name: material
  features:
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
  language: en

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html

plugins:
  - search

nav:
  - Home: index.md
  - Terraform: terraform.md
  - Set Up Workflows: setup_workflows.md
  - Application Overview: application_overview.md
  - Migrations: migrations.md
  - Authentication: authentication.md
